# Site settings
course_name: "ESE6150: F1Tenth Autonomous Racing Cars"
course_description: "This hands-on course is for graduate students interested in the fields of robot perception, motion planning, control theory, and autonomous systems. It is also for students interested in the burgeoning field of autonomous driving. This course introduces the students to the hardware, software and algorithms involved in building and racing an autonomous race car. Every week, students participate in two lectures and complete an extensive hands-on lab. By week 6, the students will have built, programmed and driven a 1/10th scale autonomous race car, and learned fundamental principles in reactive planning. By week 10, they will learn simultaneous localization and mapping and efficient planning using pure pursuit. By week 16, students will develop and implement advanced racing strategies that will give their team the edge in the race that concludes the course. Topics include: selfdriving hardware, Robot Operating System, Electronic Speed Control, localization, scan matching, PID control, mapping, SLAM, racing lines, neural networks-based autonomous cars, visual feature extraction, autonomous transportation systems, learning based visual navigation, model-predictive control and ethical/moral decision making"
course_semester: "Spring 2024"

baseurl: "/ese6150sp2024" # the subpath of your site, e.g. /blog/
url: "http://AhmadAmine998.github.io/" # the base hostname & protocol for your site

schoolname: "University of Pennsylvania"
schoolurl: "https://www.ese.upenn.edu/"
twitter_username: xlab_upenn

address: |
    3330 Walnut St
    Philadelphia, PA 19104
    USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
